version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp:0.31.0
    steps:
      - run: 
          name: "Set NEMU_CPP environment variable and create workspace directory"
          command: mkdir -p /projects/nemu/cpp && echo 'export NEMU_CPP="/projects/nemu/cpp"' >> $BASH_ENV
      - run:
          name: "Install build dependency: Nemu/C++ WebFramework"
          command: cd /projects/nemu/cpp && git clone https://github.com/nemu-cpp/web-framework.git && cd web-framework/build/gnumake && make
      - checkout:
          path: /projects/nemu/cpp/debug-server
      - run:
          name: "Build: Nemu Debug Server"
          command: cd /projects/nemu/cpp/debug-server/build/gnumake && make
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
